### ISSUE TITLE
Error in webtagging

### ISSUE THREAD

**Issue by pwalczysko** [MicronOxford/webtagging#21]
Go to trout latest, any user. Find Project ``5.0 data``, expand, find the dataset ``leica-original`` and select it.
Change to ``Auto Tag`` in central pane.(Observe that the list is not loaded properly with tags suggestions, filing a special issue for this as well). 

Tick the ``Path`` tickbox, now the columns are displayed in the central pane.
Click ``Apply``
Observe error.

```
Traceback (most recent call last):

  File "/opt/hudson/workspace/OMERO-5.1-latest-deploy/src/dist/lib/python/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/opt/hudson/workspace/OMERO-5.1-latest-deploy/src/dist/lib/python/omeroweb/decorators.py", line 469, in wrapped
    retval = f(request, *args, **kwargs)

  File "/opt/hudson/workspace/OMERO-5.1-latest-deploy/src/dist/lib/python/omeroweb/decorators.py", line 519, in wrapper
    context = f(request, *args, **kwargs)

  File "/home/hudson/OMERO.webapps/autotag/views.py", line 769, in process_update
    createTagAnnotationsLinks(conn, additions, removals)

  File "/home/hudson/OMERO.webapps/autotag/utils.py", line 56, in createTagAnnotationsLinks
    conn.SERVICE_OPTS

  File "/opt/hudson/workspace/OMERO-5.1-latest-deploy/src/dist/lib/python/omero/gateway/__init__.py", line 4123, in __call__
    return self.handle_exception(e, *args, **kwargs)

  File "/opt/hudson/workspace/OMERO-5.1-latest-deploy/src/dist/lib/python/omeroweb/webclient/webclient_gateway.py", line 2069, in handle_exception
    e, *args, **kwargs)

  File "/opt/hudson/workspace/OMERO-5.1-latest-deploy/src/dist/lib/python/omero/gateway/__init__.py", line 4120, in __call__
    return self.f(*args, **kwargs)

  File "/opt/hudson/workspace/OMERO-5.1-latest-deploy/src/dist/lib/python/omero_api_IUpdate_ice.py", line 155, in saveAndReturnArray
    return _M_omero.api.IUpdate._op_saveAndReturnArray.invoke(self, ((graph, ), _ctx))

SecurityViolation: exception ::omero::SecurityViolation
{
    serverStackTrace = ome.conditions.SecurityViolation: Group is rwr---. Cannot link to object: ome.model.annotations.TagAnnotation:Id_31251
	at ome.security.basic.OmeroInterceptor.throwIfNotGranted(OmeroInterceptor.java:1149)
	at ome.security.basic.OmeroInterceptor.evaluateLinkages(OmeroInterceptor.java:553)
	at ome.security.basic.OmeroInterceptor.onSave(OmeroInterceptor.java:161)
	at org.hibernate.event.def.AbstractSaveEventListener.substituteValuesIfNecessary(AbstractSaveEventListener.java:414)
	at org.hibernate.event.def.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:293)
	at org.hibernate.event.def.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:204)
	at org.hibernate.event.def.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:144)
	at org.hibernate.event.def.DefaultMergeEventListener.saveTransientEntity(DefaultMergeEventListener.java:415)
	at org.hibernate.event.def.DefaultMergeEventListener.mergeTransientEntity(DefaultMergeEventListener.java:341)
	at org.hibernate.event.def.DefaultMergeEventListener.entityIsTransient(DefaultMergeEventListener.java:303)
	at org.springframework.orm.hibernate3.support.IdTransferringMergeEventListener.entityIsTransient(IdTransferringMergeEventListener.java:59)
	at ome.security.basic.MergeEventListener.entityIsTransient(MergeEventListener.java:161)
	at org.hibernate.event.def.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:258)
	at ome.security.basic.MergeEventListener.onMerge(MergeEventListener.java:94)
	at org.hibernate.event.def.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:84)
	at ome.security.basic.MergeEventListener.onMerge(MergeEventListener.java:80)
	at org.hibernate.impl.SessionImpl.fireMerge(SessionImpl.java:861)
	at org.hibernate.impl.SessionImpl.merge(SessionImpl.java:845)
	at org.hibernate.impl.SessionImpl.merge(SessionImpl.java:849)
	at ome.logic.UpdateImpl.internalMerge(UpdateImpl.java:274)
	at ome.logic.UpdateImpl$4.run(UpdateImpl.java:148)
	at ome.logic.UpdateImpl$4.run(UpdateImpl.java:143)
	at ome.logic.UpdateImpl.doAction(UpdateImpl.java:312)
	at ome.logic.UpdateImpl.doAction(UpdateImpl.java:303)
	at ome.logic.UpdateImpl.saveAndReturnArray(UpdateImpl.java:143)
	at sun.reflect.GeneratedMethodAccessor1772.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:307)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at ome.security.basic.EventHandler.invoke(EventHandler.java:154)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.orm.hibernate3.HibernateInterceptor.invoke(HibernateInterceptor.java:111)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:108)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at ome.tools.hibernate.ProxyCleanupFilter$Interceptor.invoke(ProxyCleanupFilter.java:249)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at ome.services.util.ServiceHandler.invoke(ServiceHandler.java:116)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
	at com.sun.proxy.$Proxy93.saveAndReturnArray(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor1772.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:307)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at ome.security.basic.BasicSecurityWiring.invoke(BasicSecurityWiring.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at ome.services.blitz.fire.AopContextInitializer.invoke(AopContextInitializer.java:43)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
	at com.sun.proxy.$Proxy93.saveAndReturnArray(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor2294.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at ome.services.blitz.util.IceMethodInvoker.invoke(IceMethodInvoker.java:179)
	at ome.services.throttling.Callback.run(Callback.java:56)
	at ome.services.throttling.InThreadThrottlingStrategy.callInvokerOnRawArgs(InThreadThrottlingStrategy.java:56)
	at ome.services.blitz.impl.AbstractAmdServant.callInvokerOnRawArgs(AbstractAmdServant.java:149)
	at ome.services.blitz.impl.UpdateI.saveAndReturnArray_async(UpdateI.java:58)
	at sun.reflect.GeneratedMethodAccessor2293.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:307)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at omero.cmd.CallContext.invoke(CallContext.java:78)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
	at com.sun.proxy.$Proxy94.saveAndReturnArray_async(Unknown Source)
	at omero.api._IUpdateTie.saveAndReturnArray_async(_IUpdateTie.java:89)
	at omero.api._IUpdateDisp.___saveAndReturnArray(_IUpdateDisp.java:245)
	at omero.api._IUpdateDisp.__dispatch(_IUpdateDisp.java:375)
	at IceInternal.Incoming.invoke(Incoming.java:159)
	at Ice.ConnectionI.invokeAll(ConnectionI.java:2357)
	at Ice.ConnectionI.dispatch(ConnectionI.java:1208)
	at Ice.ConnectionI.message(ConnectionI.java:1163)
	at IceInternal.ThreadPool.run(ThreadPool.java:302)
	at IceInternal.ThreadPool.access$300(ThreadPool.java:12)
	at IceInternal.ThreadPool$EventHandlerThread.run(ThreadPool.java:643)
	at java.lang.Thread.run(Thread.java:744)

    serverExceptionClass = ome.conditions.SecurityViolation
    message = Group is rwr---. Cannot link to object: ome.model.annotations.TagAnnotation:Id_31251
}


<WSGIRequest
path:/latest/autotag/auto_tag/processUpdate/,
GET:<QueryDict: {}>,
POST:<QueryDict: {u'imagechecked': [u'token_21749_petr', u'token_21749_Users', u'token_21749_5.0 data', u'token_21749_4D-series', u'token_21755_petr', u'token_21755_Users', u'token_21755_5.0 data', u'token_21755_8x binning int 125x50 286fps', u'token_21750_petr', u'token_21750_Users', u'token_21750_5.0 data', u'token_21751_petr', u'token_21751_Users', u'token_21751_5.0 data', u'token_21754_petr', u'token_21754_Users', u'token_21754_5.0 data', u'token_21753_petr', u'token_21753_Users', u'token_21753_5.0 data', u'token_21753_multi-channel', u'token_21757_petr', u'token_21757_Users', u'token_21757_5.0 data', u'token_21752_petr', u'token_21752_Users', u'token_21752_5.0 data', u'token_21756_petr', u'token_21756_Users', u'token_21756_5.0 data'], u'tag-selector': [u'petr_31254', u'Users_31252', u'5.0 data_31251', u'multi-channel_31584', u'8x binning int 125x50 286fps_31583', u'4D-series_31582']}>,
COOKIES:{'csrftoken': 'fkgHK6V95XgNyPxg49rt6ChhStGxesxv',
 'sessionid_OMERO-5.1-latest-deploy': 'xgr8jqcsi8hzbtrbym6r9wpa3ghrzljh'},
META:{'CONTENT_LENGTH': '1169',
 'CONTENT_TYPE': 'application/x-www-form-urlencoded; charset=UTF-8',
 u'CSRF_COOKIE': u'fkgHK6V95XgNyPxg49rt6ChhStGxesxv',
 'HTTPS': 'on',
 'HTTP_ACCEPT': 'application/json, text/javascript, */*; q=0.01',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_ACCEPT_LANGUAGE': 'en-GB,en;q=0.5',
 'HTTP_CACHE_CONTROL': 'no-cache',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_CONTENT_LENGTH': '1169',
 'HTTP_CONTENT_TYPE': 'application/x-www-form-urlencoded; charset=UTF-8',
 'HTTP_COOKIE': 'csrftoken=fkgHK6V95XgNyPxg49rt6ChhStGxesxv; sessionid_OMERO-5.1-latest-deploy=xgr8jqcsi8hzbtrbym6r9wpa3ghrzljh',
 'HTTP_HOST': 'trout.openmicroscopy.org',
 'HTTP_PRAGMA': 'no-cache',
 'HTTP_REFERER': 'https://trout.o...y.org/latest/webclient/',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:33.0) Gecko/20100101 Firefox/33.0',
 'HTTP_X_CSRFTOKEN': 'fkgHK6V95XgNyPxg49rt6ChhStGxesxv',
 'HTTP_X_REQUESTED_WITH': 'XMLHttpRequest',
 'PATH_INFO': u'/autotag/auto_tag/processUpdate/',
 'QUERY_STRING': '',
 'REQUEST_METHOD': 'POST',
 'SCRIPT_INFO': '/latest',
 'SCRIPT_NAME': u'/latest',
 'SERVER_NAME': 'ome-c6100-3',
 'SERVER_PORT': '443',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'wsgi.errors': <flup.server.fcgi_base.TeeOutputStream object at 0x6429a90>,
 'wsgi.input': <flup.server.fcgi_base.InputStream object at 0x6429f90>,
 'wsgi.multiprocess': True,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'https',
 'wsgi.version': (1, 0)}>
```

**Comment by pwalczysko** [comment]
cc @joshmoore @aleksandra-tarkowska

**Comment by pwalczysko** [comment]
Could reproduce for user-10, user-11

**Comment by pwalczysko** [comment]
Now I can reproduce only for user-10 in read-only.

**Comment by aleksandra-tarkowska** [comment]
The failing view is

```
POST https://trout.openmicroscopy.org/latest/autotag/auto_tag/processUpdate/
"NetworkError: 500 INTERNAL SERVER ERROR - https://trout.openmicroscopy.org/latest/autotag/auto_tag/processUpdate/"
```

**Comment by aleksandra-tarkowska** [comment]
as inspected with @pwalczysko failing on 5.0 and 4.4 data in read-only group only

**Comment by pwalczysko** [comment]
The bug here has to do with TAGS of other people in Read-only group. Webtagging suggests tags of other people even in Read-only group. The users in Read-only group have no right to use other people's tags,  When ``Apply`` is clicked, crash happens. This is not happening in private, read-annotate or read-write groups, where this bug never appears.

Workflow to repeat:
  - have two members (not admins, not owners) in Read-only group 
  - import couple of ``test_images_good/ome-tiff`` images for each of those two members
  - use webtagging on this newly imported dataset for one of the members, Apply as many tags as you can
  - repeat the webtagging for the other member, again Apply as many tags as you can (do not change the suggested tags, at this stage webtagging is suggesting the tags of the other member)
  - observe ERROR

**Comment by pwalczysko** [comment]
This bug is on octopus (with the old webtagging version) as well -> not a regression.

**Comment by pwalczysko** [comment]
@will-moore @joshmoore

**Comment by dpwrussell** [comment]
Hi all. Good investigation @pwalczysko!

I see why there is a problem with other users tags in a read-only group and I can fix it very easily. I actually have an optimization to add on that query anyway which should speed up webtagging quite a lot.

However, I am wondering if this behaviour is actually what is intended? I.e. should it be impossible to use other users tags in a read-only group? I can see why it would be, but also maybe why it wouldn't be.
I guess it comes down to whether the read-only refers to the data, or to everything.

**Comment by pwalczysko** [comment]
@dpwrussell : Read-only refers to everything. This means something OMERO calls ``CanAnnotate`` (possibly wrong syntax, sorry) - this is simply false for other users Tags (which are ruled by the same rules as annotations) and is a part of OMERO permissions system. If we would want to change it, we would have to change very deep-going things about OMERO. This would not happen soon.

I guess that the problem is not that sharp because the user can easily create her/his own tags using your excellent tool. :)

**Comment by dpwrussell** [comment]
@pwalczysko Ok, that's fine. I will make a change to remove tags that are in a read-only group that do not belong to the querying user.

**Comment by pwalczysko** [comment]
@dpwrussell Do you want to do the change prior to the compatibility-with-5.1 release ? This was discussed to happen tomorrow (atm the released version of webtagging and OMERO 5.1 are completely not-compatilble and webtagging would be fully unusable)

**Comment by pwalczysko** [comment]
/ @sbesson

**Comment by dpwrussell** [comment]
I can probably get that done today so yes, that would make sense. The other bugs will probably have to wait though.

**Comment by dpwrussell** [comment]
@pwalczysko @sbesson Previously, when webtagging was under my personal banner, webtagging PRs were being merged in during the merge build, but I'm not sure if that is still the case. So we'll have to see tomorrow if this PR can be tested on trout etc.

**Comment by sbesson** [comment]
@dpwrussell: the webtaggin merge build should now merge all PRs opened by members of the organization by default. So I definitely expect this PR to be deployed on the CI servers tomorrow morning. I will double check
